name: Zola on GitHub Pages
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3.0.0
            - name: deploy_zola
              uses: shalzz/zola-deploy-action@v0.16.1
              env:
                PAGES_BRANCH: pages
                TOKEN: ${{ secrets.ZOLA_BLOG }}
